name: snapshot
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm install
      - run: node scripts/snapshot.mjs
      - uses: actions/upload-artifact@v4
        with:
          name: snapshot
          path: SNAPSHOT.json
